- shell:
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt update && sudo apt upgrade

- shell:
  - sudo apt --assume-yes install curl
  - sudo apt --assume-yes remove cmdtest; sudo apt --assume-yes install yarn
  - sudo apt --assume-yes install zsh

- shell:
  - sudo snap install code --classic
  - sudo snap install docker
  - sudo snap install http
  - sudo snap install kubectl --classic
  - sudo snap install postman
  - sudo snap install slack --classic
  - sudo snap install spotify
  - sudo snap install telegram-desktop
